# Generated by Django 3.0 on 2020-05-23 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_uid', models.CharField(max_length=50, verbose_name='文章UID')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('allow_email', models.BooleanField(default=True, verbose_name='有回复时通过邮件通知')),
                ('is_pub', models.BooleanField(default=True, verbose_name='发布')),
                ('content', models.TextField(verbose_name='评论')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='评论者IP')),
                ('ua', models.CharField(blank=True, max_length=200, null=True, verbose_name='UA')),
                ('at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.Comment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
